sushi_proj/sushi_app/urls.py
from django.urls import path
from sushi_app.views import store, analyze_exe, get_gender_popular

app_name = 'sushi_app'

urlpatterns = [
    path(
        'store',
        store.list_view,
        name='store_list'),
    path(
        'store/<slug:store_id>',
        store.detail_view,
        name='store_detail'),
    path('save-review', store.save_review),
    path('review-save', store.save_review),
    path('keyword-sort/<str:keyword>/<slug:site>',
         store.keyword_sort, name='keyword_sort'),
    path('store-search', store.store_search, name='store_search'),
    path('area-search', store.area_search, name='area_search'),
    path('exe', analyze_exe.implement_all_process, name="exe"),
    path('top-growth-rate', store.get_top_growth_rate, name="top_growth_rate"),
    path(
        'gender-rate/is_dinner=<slug:is_dinner>/is_male=<slug:is_male>',
        get_gender_popular.get_popular_store,
        name="get_gender_popular"),
]

sushi_proj/sushi_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from sushi_app.views.top_page import show_top_page


def render_index(request):
    return render(request, 'index.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', show_top_page, name='show_top_page'),
    path('sushisumma/', include('sushi_app.urls')),
    # path('campaign/', include('marry_app.urls', namespace='campaign')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sushi_proj/templates/base.html
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <title>SushiSumma</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'sushi_app/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="{% static 'sushi_app/css/styles.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
        integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
        crossorigin="" />
    <link rel="stylesheet" href="{% static 'sushi_app/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'sushi_app/css/homepage.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
        integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
        crossorigin=""></script>

    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar">
        <h1 class="navbar-title">
            <a class="navbar-brand" href="/">SushiSumma</a>
        </h1>
        <div class="nav-container">
            <form class="search-box" action="{% url 'sushi_app:store_search' %}" method="get">
                {% csrf_token %}
                <div class="input-container">
                    <img src="{% static 'sushi_app/icons/search_icon.svg' %}" alt="img">
                    <input class="search-textbox" type="text" name="search" placeholder="search store">
                    <!-- <input type="submit" class="btn search-button" value="検索"> -->
                </div>
            </form>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {{ content }}
        {% endblock %}
        {% block extra_js %}{% endblock %}

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; SushiSumma 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- <script type="text/javascript" src="{% static 'sushi_app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->
    -->
    <script type="text/javascript" src="{% static 'sushi_app/js/index.js' %}"></script>
    <script type="text/javascript" src="{% static 'sushi_app/js/gulpfile.js' %}"></script>
</body>

</html>

sushi_proj/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}SushiSumma{% endblock title %}
{% block content %}


<!-- Page Content -->
<div class="container">
    <div class="area-container">
        <p>エリアを選ぶ</p>
        <div class="area-icon-container">
            <img src="{% static 'sushi_app/icons/lower_arrow.svg' %}" alt="arrow" class="icon lower-arrow-icon" />
            <form class="area-select" action="{% url 'sushi_app:area_search' %}" method="get">
                <select name="prefecture" class="prefecture-list prefecture-item" id="">
                    {% for prefecture in prefecture_list %}
                    <option value={{ prefecture }}>{{ prefecture }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="submit" class="btn-primary prefecture-item" />
            </form>
        </div>
    </div>
    <br>
    <a class="keyword-link" href="{% url 'sushi_app:store_list' %}">store list</a>
    <div class="keyword-container">
        <div class="keyword-title-container">
            <img src="{% static 'sushi_app/icons/database.svg' %}" alt="database-icon" class="icon"></img>
            <h4 class="title-with-icon">keywordから寿司を見る</h4>
        </div>
        <div class="keyword-box-container">
            {% for keyword_list in keywords_list %}
            <div class="keyword-box">
                <p><a class="keyword"
                        href="{% url 'sushi_app:keyword_sort' keyword=keyword_list.0 site='tabelog' %}">{{ keyword_list.0 }}</a>
                </p>
            </div>
            {% endfor %}
            <p><a href="{% url 'sushi_app:top_growth_rate' %}">急上昇</a></p>
            <p><a href="{% url 'sushi_app:get_gender_popular' is_dinner=True is_male=True %}">男性ウケ</a></p>
            <p><a href="{% url 'sushi_app:get_gender_popular' is_dinner=True is_male=False %}">女性ウケ</a></p>
        </div>
    </div>
</div>
<!-- /.container -->


{% endblock content %}