sushi_proj/sushi_app/urls.py
from django.urls import path
from sushi_app.views import store, analyze_exe, get_gender_popular

app_name = 'sushi_app'

urlpatterns = [
    path(
        'store',
        store.list_view,
        name='store_list'),
    path(
        'store/<slug:store_id>',
        store.detail_view,
        name='store_detail'),
    path('save-review', store.save_review),
    path('review-save', store.save_review),
    path('keyword-sort/<str:keyword>/<slug:site>',
         store.keyword_sort, name='keyword_sort'),
    path('store-search', store.store_search, name='store_search'),
    path('area-search', store.area_search, name='area_search'),
    path('exe', analyze_exe.implement_all_process, name="exe"),
    path('top-growth-rate', store.get_top_growth_rate, name="top_growth_rate"),
    path(
        'gender-rate/is_dinner=<slug:is_dinner>/is_male=<slug:is_male>',
        get_gender_popular.get_popular_store,
        name="get_gender_popular"),
]

sushi_proj/sushi_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from sushi_app.views.top_page import show_top_page


def render_index(request):
    return render(request, 'index.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', show_top_page, name='show_top_page'),
    path('sushisumma/', include('sushi_app.urls')),
    # path('campaign/', include('marry_app.urls', namespace='campaign')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sushi_proj/sushi_app/models/dinner_summary_average.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from .store_model import Store


class DinnerSummaryAverage(models.Model):
    class Meta:
        verbose_name = 'dinner_summary_average'
        verbose_name_plural = 'dinner_summary_average'
    id = models.CharField(
        'dinner_summary_average',
        max_length=10,
        primary_key=True)
    keyword = models.CharField('keyword', max_length=30, null=True)
    keyword_sentiment_ave_score = models.FloatField(
        'sentiment_ave_score', null=True)

sushi_proj/sushi_app/models/retty_model.py
from django.db import models


class Retty(models.Model):
    class Meta:
        verbose_name = 'retty'
        verbose_name = 'retty'
    id = models.IntegerField('rettyID', primary_key=True)
    score = models.FloatField('retty_score')
    phone_num = models.CharField('電話番号', max_length=20)
    name = models.CharField('name', max_length=30, null=True)

    def __str__(self):
        return 'retty ' + str(self.score)

sushi_proj/sushi_app/views/analyze_exe.py
from sushi_app.models.store_model import Store
# /sushi_proj/sushi_app/models/store_model.py
from sushi_app.models.review_model import Review
from sushi_app.models.sentiment_result_model import LunchSentimentResult, DinnerSentimentResult
from sushi_app.models.important_word_model import LunchImportantWords, DinnerImportantWords
from sushi_app.models.store_summary import DinnerStoreSummary, LunchStoreSummary
from sushi_app.models.dinner_summary_average import DinnerSummaryAverage
from sushi_app.models.score_history_model import TabelogHistory, RettyHistory
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect
from sushi_proj.settings import BASE_DIR, GCP_API_KEY
from get_important_word.analysis import Analyzer
from django.http import HttpResponse
from statistics import mean
import json
# from django.http import JsonResponse


class AnalyzeExe:
    def __init__(self, keyword_dict, adjective_dict, is_dinner):
        self.keyword_dict = keyword_dict
        self.adjective_dict = adjective_dict
        self.is_dinner = is_dinner

    def get_store_id_list(self):
        store_obj_list = Store.objects.all()
        store_id_list = []
        for store_obj in store_obj_list:
            store_id = store_obj.id
            store_id_list.append(store_id)
        return store_id_list

    def implement_all(self, store_id_list):
        for store_id in store_id_list:
            self.get_important_word(store_id, self.is_dinner)
            self.get_sentiment_result(store_id, self.is_dinner)
            self.get_posinega(store_id, self.is_dinner)
        self.get_summary_average(self.is_dinner, self.keyword_dict)
        self.update_growth_rate()

    def get_important_word(self, store_id, is_dinner):
        # decide dinner or lunch
        if is_dinner:
            # delete old data
            DinnerImportantWords.objects.filter(
                store__id__exact=store_id).delete()
        # 各店舗のレビューが入ったリストを格納
            dinner_reviews = Review.objects.filter(
                store__id__exact=store_id).filter(ld_id__exact=1)
            dinner_reviews_list = []
            for dinner_review in dinner_reviews:
                review_content = dinner_review.review
                dinner_reviews_list.append(review_content)
            content = ''.join(dinner_reviews_list)
            analyzer = Analyzer()
            temp = analyzer.feature_analysis_adjective(
                content, self.keyword_dict, self.adjective_dict)
            store = get_object_or_404(Store, id=store_id)
            for t in temp:
                try:
                    max_id = DinnerImportantWords.objects.latest('id').id
                except ObjectDoesNotExist:
                    max_id = 'DI00000'

                dinner_important_words_id = 'DI' + \
                    (str(int(max_id[2:]) + 1).zfill(5))

                # 例：['赤酢', 0, ['強い', 0], ['あっさり', 0], ['すっぱい', 0]]
                key_words = t[0]
                key_words_nums = t[1]
                keyword_modifier1 = t[2]
                keyword_modifier2 = t[3]
                if len(t) > 4:
                    keyword_modifier3 = t[4]
                else:
                    keyword_modifier3 = []
                DinnerImportantWords.objects.create(
                    id=dinner_important_words_id,
                    store=store,
                    key_words=key_words,
                    key_words_nums=key_words_nums,
                    keyword_modifier1=keyword_modifier1,
                    keyword_modifier2=keyword_modifier2,
                    keyword_modifier3=keyword_modifier3)
        else:
            LunchImportantWords.objects.all().delete()
            lunch_reviews = Review.objects.filter(
                store__id__exact=store_id).filter(ld_id__exact=0)
            lunch_reviews_list = []
            for lunch_review in lunch_reviews:
                temp = lunch_review.review
                lunch_reviews_list.append(temp)
            content = ''.join(lunch_reviews_list)
            analyzer = Analyzer()
            temp = analyzer.feature_analysis_adjective(
                content, self.keyword_dict)
            store = get_object_or_404(Store, id=store_id)
            for t in temp:
                try:
                    max_id = LunchImportantWords.objects.latest('id').id
                except ObjectDoesNotExist:
                    max_id = 'DI00000'

                lunch_important_words_id = 'DI' + \
                    (str(int(max_id[2:]) + 1).zfill(5))

                # 例：['赤酢', 0, ['強い', 0], ['あっさり', 0], ['すっぱい', 0]]
                key_words = t[0]
                key_words_nums = t[1]
                keyword_modifier1 = t[2]
                keyword_modifier2 = t[3]
                keyword_modifier3 = t[4]
                LunchImportantWords.objects.create(
                    id=lunch_important_words_id,
                    store=store,
                    key_words=key_words,
                    key_words_nums=key_words_nums,
                    keyword_modifier1=keyword_modifier1,
                    keyword_modifier2=keyword_modifier2,
                    keyword_modifier3=keyword_modifier3)

                # return render(self, 'sushi_app/sample.html', {'temp': temp})

                # 感情値を取得

    def get_sentiment_result(self, store_id, is_dinner):
        if is_dinner:
            dinner_reviews = Review.objects.filter(
                store__id__exact=store_id).filter(
                ld_id__exact=1)  # review object
            store = get_object_or_404(Store, id=store_id)  # ストアオブジェクト
            # import api key from settings
            key = GCP_API_KEY
            analyzer = Analyzer()
            gcp_nums = 0
            for dinner_review in dinner_reviews:
                if not dinner_review.is_new:
                    continue
                text = dinner_review.review
                sentiment_result = analyzer.gcp_analyzer(text, key)
                gcp_nums += 1
                print("gcp nums === " + str(gcp_nums))
                for elem in sentiment_result:
                    try:
                        max_id = DinnerSentimentResult.objects.latest('id').id
                    except ObjectDoesNotExist:
                        max_id = 'DSR0000000000'
                    dinner_sentiment_result_id = 'DSR' + \
                        (str(int(max_id[3:]) + 1).zfill(10))
                    sentense = elem[0]
                    magnitude = elem[1]
                    sentiment = elem[2]
                    review = dinner_review
                    DinnerSentimentResult.objects.create(
                        id=dinner_sentiment_result_id,
                        sentense=sentense,
                        sentiment=sentiment,
                        magnitude=magnitude,
                        review=review,
                        store=store)
                dinner_review.is_new = False
                dinner_review.save()
        # return HttpResponse('hello')
        else:
            lunch_reviews = Review.objects.filter(
                store__id__exact=store_id).filter(
                ld_id__exact=0)  # review object
            store = get_object_or_404(Store, id=store_id)  # ストアオブジェクト
            key = GCP_API_KEY
            analyzer = Analyzer()
            for lunch_review in lunch_reviews:
                text = lunch_review.review
                sentiment_result = analyzer.gcp_analyzer(text, key)
                for elem in sentiment_result:
                    try:
                        max_id = LunchSentimentResult.objects.latest('id').id
                    except ObjectDoesNotExist:
                        max_id = 'DSR0000000000'
                    lunch_sentiment_result_id = 'DSR' + \
                        (str(int(max_id[3:]) + 1).zfill(10))
                    sentense = elem[0]
                    magnitude = elem[1]
                    sentiment = elem[2]
                    review = lunch_review
                    LunchSentimentResult.objects.create(
                        id=lunch_sentiment_result_id,
                        sentense=sentense,
                        sentiment=sentiment,
                        magnitude=magnitude,
                        review=review,
                        store=store)

    # 以下でポジネガを取得

    def get_posinega(self, store_id, is_dinner):
        store = get_object_or_404(Store, id=store_id)
        if is_dinner:
            # delete old data
            DinnerStoreSummary.objects.filter(
                store__id__exact=store_id).delete()
            sentiment_result_objects = DinnerSentimentResult.objects.filter(
                store__id__exact=store_id)
            # (ex):[["まぐろが美味しいです", 0.3, 0.7], ["hoge", 0.3, 0.5]]
            parse_list = []
            for sentiment_result_object in sentiment_result_objects:
                text = sentiment_result_object.sentense
                sentiment = sentiment_result_object.sentiment
                magnitude = sentiment_result_object.magnitude
                sentiment_list = [text, magnitude, sentiment]
                parse_list.append(sentiment_list)
            analyzer = Analyzer()
            # ["まぐろ":[["うまい", 0.2, 0.5]["くさい", 0.5, -0.2]]
            posi_nega_result, sentiment_dic = analyzer.get_posinega_adjective(
                parse_list, self.keyword_dict, self.adjective_dict)
        #  {'赤酢': [['強い', 0.0, 0.0], ['あっさり', 0.0, 0.0], ['すっぱい', 0.0, 0.0]], '握り': [['大きい', 0.48999999999999994, 0.0], ['小さい', 0.0, 0.0], ['創作', 0.0, 0.0]], 'シャリ': [['大きい', 0.0, 0.0], ['小さい', 0.0, 0.0], ['パラパラ', 0.0, 0.0], ['塩気', 0.0, 0.0], ['甘い', 0.0, 0.0], ['熟成', 0.0, 0.0]]})
        #    {'赤酢': [0.4, 0.4], }
            for keyword in posi_nega_result:
                try:
                    max_id = DinnerStoreSummary.objects.latest('id').id
                except ObjectDoesNotExist:
                    max_id = 'DSS0000000000'

sushi_proj/sushi_app/views/get_average.py
from sushi_app.models.dinner_summary_average import DinnerSummaryAverage


def get_keyword_average(keyword):
    average_obj = DinnerSummaryAverage.objects.get(keyword__exact=keyword)
    return average_obj.keyword_sentiment_ave_score

sushi_proj/sushi_app/views/get_gender_popular.py
from sushi_app.models.store_model import Store
from sushi_app.models.review_model import Review
from django.shortcuts import render


def get_popular_store(request, is_dinner, is_male):
    store_list = Store.objects.all()
    result_list = []
    if is_dinner:
        for store in store_list:
            result_list.append(get_gender_ave(store))
    if is_male:
        sorted_result_list = sorted(
            result_list,
            reverse=True,
            key=lambda result: result[1])
    else:
        sorted_result_list = sorted(
            result_list,
            reverse=True,
            key=lambda result: result[2])
    return render(request, 'sushi_app/gender_sorted_list.html',
                  {'sorted_result_list': sorted_result_list})


def get_gender_ave(store):
    all_reviews = Review.objects.filter(store_id__exact=store.id)
    male_reviews_list = [
        review for review in all_reviews if review.user_sex == 1]
    female_reviews_list = [
        review for review in all_reviews if review.user_sex == 2]
    unknown_reviews_list = [
        review for review in all_reviews if review.user_sex == 0]
    if male_reviews_list:
        male_score_ave = sum(
            male_review.score for male_review in male_reviews_list) / len(male_reviews_list)
    else:
        male_score_ave = 0
    if female_reviews_list:
        female_score_ave = sum(
            female_review.score for female_review in female_reviews_list) / len(female_reviews_list)
    else:
        female_score_ave = 0
    return [store, male_score_ave, female_score_ave]


def get_gender_rate(store_id, is_dinner):
    if is_dinner:
        all_reviews = Review.objects.filter(store_id__exact=store_id)
        male_reviews_list = [
            review for review in all_reviews if review.user_sex == 1]
        female_reviews_list = [
            review for review in all_reviews if review.user_sex == 2]
        unknown_reviews_list = [
            review for review in all_reviews if review.user_sex == 0]
        if male_reviews_list:
            male_rate = len(male_reviews_list) / len(all_reviews)
        else:
            male_rate = 0
        if female_reviews_list:
            female_rate = len(female_reviews_list) / len(all_reviews)
        else:
            female_rate = 0
        if unknown_reviews_list:
            unknown_rate = len(unknown_reviews_list) / len(all_reviews)
        else:
            unknown_rate = 0
        return [
            male_rate,
            female_rate,
            unknown_rate]

sushi_proj/sushi_app/views/top_page.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from sushi_proj.settings import BASE_DIR
import json
from collections import defaultdict

prefecture_list = ["北海道",
                   "青森県",
                   "岩手県",
                   "宮城県",
                   "秋田県",
                   "山形県",
                   "福島県",
                   "茨城県",
                   "栃木県",
                   "群馬県",
                   "埼玉県",
                   "千葉県",
                   "東京都",
                   "神奈川県",
                   "新潟県",
                   "富山県",
                   "石川県",
                   "福井県",
                   "山梨県",
                   "長野県",
                   "岐阜県",
                   "静岡県",
                   "愛知県",
                   "三重県",
                   "滋賀県",
                   "京都府",
                   "大阪府",
                   "兵庫県",
                   "奈良県",
                   "和歌山県",
                   "鳥取県",
                   "島根県",
                   "岡山県",
                   "広島県",
                   "山口県",
                   "徳島県",
                   "香川県",
                   "愛媛県",
                   "高知県",
                   "福岡県",
                   "佐賀県",
                   "長崎県",
                   "熊本県",
                   "大分県",
                   "宮崎県",
                   "鹿児島県",
                   "沖縄県"]


def show_top_page(request):

    json_file = BASE_DIR + '/analyze_files/dictionary.json'

    with open(json_file, encoding='utf-8') as f:
        json_data = json.load(f)
        keywords = json_data["all_jiku"]["all_jiku_list"]
        keywords_list = []
        for keyword in keywords:
            if json_data["all_jiku"][keyword]["adjective"]:
                modi_words = json_data["all_jiku"][
                    keyword]["syusyoku_list"]
            else:
                modi_words = []
            keywords_list.append([keyword, modi_words])

        return render(
            request, 'index.html', {
                "keywords_list": keywords_list, "prefecture_list": prefecture_list})

sushi_proj/sushi_app/templates/sushi_app/gender_sorted_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}sushi_stores{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Sushiの一覧</h4>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">StoreName</th>
            <th scope="col">Store_Summary</th>
        </tr>
    </thead>
    <tbody>
        {% for result_list in sorted_result_list %}

        <tr>
            <th scope="row">
                <a href="{% url 'sushi_app:store_detail' store_id=result_list.0.id %}">
                    {{ result_list.0.store_name }}

                </a>
            <td>
                男性ウケ：{{ result_list.1 }}
            </td>
            <td>
                女性ウケ：{{ result_list.2 }}
            </td>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

sushi_proj/sushi_app/templates/sushi_app/growth_rate_store_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}sushi_stores{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Sushiの一覧</h4>


<table class="table table-striped table-bordered">
    {% if message %}
    {{ message }}
    {% endif %}
    <thead>
        <tr>
            <th scope="col">StoreID</th>
            <th scope="col">Store_Name</th>
        </tr>
    </thead>
    <tbody>
        {% for store in tabelog_store_list %}
        <tr>
            <th scope="row">
                <a href="{% url 'sushi_app:store_detail' store_id=store.id %}">
                    {{ store.id }}
                </a>
            <td>
                <p>{{ store.store_name }}</p>
            </td>
            <td>
                <p>{{ store.tabelog_growth_rate }} %</p>
            </td>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
<table class="table table-striped table-bordered">
    {% if message %}
    {{ message }}
    {% endif %}
    <thead>
        <tr>
            <th scope="col">StoreID</th>
            <th scope="col">Store_Name</th>
        </tr>
    </thead>
    <tbody>
        {% for store in retty_store_list %}
        <tr>
            <th scope="row">
                <a href="{% url 'sushi_app:store_detail' store_id=store.id %}">
                    {{ store.id }}
                </a>
            <td>
                <p>{{ store.store_name }}</p>
            </td>
            <td>
                <p>{{ retty_growth_rate }} %</p>
            </td>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% if page > 1 %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}

sushi_proj/sushi_app/templates/sushi_app/sorted_store_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}sushi_stores{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Sushiの一覧</h4>

<form action="{% url 'sushi_app:keyword_sort' keyword=keyword site='tabelog' %}" method="post">
    {% csrf_token %}
    <select name="sort" aria-placeholder="choose">
        <option value="">select</option>
        <option value="tabelog">tabelog</option>
        <option value="retty">retty</option>
    </select>
<input type="submit" class="btn btn-primary" value="submit" />
</form>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">StoreName</th>
            <th scope="col">Store_Summary</th>
        </tr>
    </thead>
    <tbody>
        {% for store_and_summary in store_summary_list %}
        <tr>
            <th scope="row">
                <a href="{% url 'sushi_app:store_detail' store_id=store_and_summary.0.id %}">
                    {{ store_and_summary.0.store_name }}

                </a>
                <td>
                    {{ store_and_summary.1.keyword }}{{ store_and_summary.1.keyword_sentiment.0 }}PP {{ store_and_summary.1.keyword_sentiment.1 }}NP
                </td>
                <td>
                    
                </td>
            </th>
                    </tr>
        {% endfor %}
    </tbody>
</table>


{% if page > 1 %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}

sushi_proj/sushi_app/templates/sushi_app/store_detail.html
{% extends "base.html" %}
{% load mathfilters %}
{% load static %}

{% block title %}Store一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Storeの詳細</h4>
<div class="store-name-container">
    <h3 class="store-name">{{ store.store_name }}</h3>
    <p class="site-score">食べログスコア：{{ store.tabelog_score }}点</p>
    <p class="site-score">Rettyスコア：{{ store.retty_score }}いきたい</p>
</div>
<div class="keyword-title-container">
    <img src="{% static 'sushi_app/icons/graph.svg' %}" alt="graph-icon" class="icon">
    <p class="title-with-icon">{{ review_length }}件のレビューを解析</p>
</div>

<p>{{ store.store_name }}の強み</p>
<canvas id="radar-chart"></canvas>
<p>{{ store.store_name }}の食べログ点数の推移</p>
<canvas id="line-chart"></canvas>
<p>{{ store.store_name }}の口コミ男女比</p>
<canvas id="pie-chart"></canvas>
<div class="gender-score-container">
    <p class="gender-score">男性客の平均スコア：{{ gender_ave_score_list.1 }}</p>
    <p class="gender-score">女性客の平均スコア：{{ gender_ave_score_list.2 }}</p>
</div>
<div class="keyword-container">

    <div class="keyword-summary-container">

        {% for summary in sorted_summary_list %}
        <div class="summary-keyword">
            <p class="posinega-keyword posinega-word">
                key: {{ summary.0 }}
            </p>
            <p class="posinega-posi posinega-score posinega-keyword-score" style="--param:{{ summary.1.0.0 }};">
                PP: {{ summary.1.0.0|floatformat }}
            </p>
            <p class="posinega-nega posinega-score posinega-keyword-score" style="--param:{{ summary.1.0.1 }};">
                NP:
                {{ summary.1.0.1|floatformat }}
            </p>
        </div>
        {% for keyword in summary.1.1 %}
        {% if keyword %}
        {% if keyword.1 is not 0 or keyword.2 is not 0 %}
        <div class="posinega-modi">
            {% if keyword.1 is not 0 and keyword.2 is not 0 %}
            <p class="posinega-word">
                {{ keyword.0 }}:
            </p>
            <p class="posinega-score posinega-posi posinega-modi-score" style="--param:{{ keyword.1 }};">
                PP{{ keyword.1|floatformat }}
            </p>
            <p class="posinega-score posinega-nega posinega-modi-score" style="--param:{{ keyword.2 }};">
                NP{{ keyword.2|floatformat }}
            </p>
            {% endif %}
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>
    <div class="store-info">
        <table class="store-detail">
            <tr>
                <td>店名</td>
                <td>{{ store.store_name }}</td>
            </tr>
            <tr>
                <td>住所</td>
                <td>{{ store.address }}</td>
            </tr>
            <tr>
                <td>最寄り駅</td>
                <td>{{ store.station }}</td>
            </tr>
            <tr>
                <td>電話番号</td>
                <td>{{ store.phone_num }}</td>
            </tr>
            <tr>
                <td>営業時間</td>
                <td>{{ store.opening_time }}</td>
            </tr>
            <tr>
                <td>定休日</td>
                <td>{{ store.regular_holiday }}</td>
            </tr>
            <tr>
                <td>Rettyスコア</td>
                <td>{{ store.retty_score }}</td>
            </tr>
            <tr>
                <td>食べログスコア</td>
                <td>{{ store.tabelog_score }}</td>
            </tr>
            <tr>
                <td>店舗詳細URL</td>
                <td>{{ store.url }}</td>
            </tr>
        </table>
    </div>
    </tbody>
</div>




{% if page > 1 %}
<a href="{% url 'sushi_app:store_detail' %}?page={{ page|sub:1 }}">back</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'sushi_app:store_detail' %}?page={{ page|add:1 }}">next</a>
{% endif %}


{% block extra_js %}

<script type="text/javascript">
    var ctx = document.getElementById("radar-chart");
    var chart_json_data = JSON.parse('{{ radar_json_data|safe }}')
    var myRadarChart = new Chart(ctx, chart_json_data);
</script>
<script type="text/javascript">
    var ctx = document.getElementById("line-chart");
    var line_json_data = JSON.parse('{{ line_json_data|safe }}')
</script>
<script type="text/javascript">
    var ctx = document.getElementById("pie-chart");
    var pie_json_data = JSON.parse('{{ pie_json_data|safe }}')
    var myPieChart = new Chart(ctx, pie_json_data);
</script>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
<script src="{% static 'sushi_app/js/map_preview.js' %}"></script>
{% endblock %}

{% endblock %}

sushi_proj/sushi_app/templates/sushi_app/store_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}sushi_stores{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">Sushiの一覧</h4>


<table class="table table-striped table-bordered">
    {% if message %}
    {{ message }}
    {% endif %}
    <thead>
        <tr>
            <th scope="col">StoreID</th>
            <th scope="col">Store_Name</th>
        </tr>
    </thead>
    <tbody>
        {% for store in stores %}
        <tr>
            <th scope="row">
                <a href="{% url 'sushi_app:store_detail' store_id=store.id %}">
                    {{ store.id }}
                </a>
                <td>
                    <p>{{ store.store_name }}</p>
                </td>
            </th>
                    </tr>
        {% endfor %}
    </tbody>
</table>


{% if page > 1 %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'sushi_app:store_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}